version: '3.2'

networks:
  dw-network:

services:

  dw-nginx:
#    image: nginx:stable-alpine
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        TZ: ${DOCKER_TIMEZONE}
    container_name: dw-nginx
    restart: always
    ports:
      - "${NGINX_PORT_SSL}:443"
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/logs:/var/log/nginx
      - ./projects:/var/www
    depends_on:
      - dw-php-7.3
      - dw-php-7.4
      - dw-php-8.0
      - dw-php-8.1
      - dw-php-8.2
      - dw-mysql-8.0
      - dw-mysql-5.7
      - dw-postgres
      - dw-mongo-4.x
      - dw-mongo-5.x
      - dw-mongo-6.x
      - dw-redis
      - dw-rabbitmq
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-5.7:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-5.7
    restart: always
    volumes:
      - ./mysql-5.7/conf.d:/etc/mysql/conf.d
      - ./mysql-5.7/data:/var/lib/mysql
      - ./mysql-5.7/logs:/var/log/mysql
      - ./mysql-5.7/dump:/dump
    ports:
      - "${MYSQL_5_7_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_5_7_ROOT_PASS}
      MYSQL_USER: ${MYSQL_5_7_USER}
      MYSQL_PASSWORD: ${MYSQL_5_7_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-8.0:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-8.0
    restart: always
    volumes:
      - ./mysql-8.0/conf.d:/etc/mysql/conf.d
      - ./mysql-8.0/data:/var/lib/mysql
      - ./mysql-8.0/logs:/var/log/mysql
      - ./mysql-8.0/dump:/dump
    ports:
      - "${MYSQL_8_0_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_8_0_ROOT_PASS}
      MYSQL_USER: ${MYSQL_8_0_USER}
      MYSQL_PASSWORD: ${MYSQL_8_0_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-postgres:
    image: postgres:alpine
    container_name: dw-postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mongo-4.x:
    image: mongo:4
    container_name: dw-mongo-4.x
    restart: always
    ports:
      - "${MONGO_4_X_PORT}:27017"
    volumes:
      - ./mongo-4.x/data:/data/db
      - ./mongo-4.x/conf:/data/configdb
      - ./mongo-4.x/dump:/dump
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mongo-5.x:
    image: mongo:5
    container_name: dw-mongo-5.x
    restart: always
    ports:
      - "${MONGO_5_X_PORT}:27017"
    volumes:
      - ./mongo-5.x/data:/data/db
      - ./mongo-5.x/conf:/data/configdb
      - ./mongo-5.x/dump:/dump
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mongo-6.x:
    image: mongo:6
    container_name: dw-mongo-6.x
    restart: always
    ports:
      - "${MONGO_6_X_PORT}:27017"
    volumes:
      - ./mongo-6.x/data:/data/db
      - ./mongo-6.x/conf:/data/configdb
      - ./mongo-6.x/dump:/dump
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-redis:
    image: redis:latest
    container_name: dw-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/var/lib/redis
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: dw-rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_CLIENT_PORT}:5672"
      - "${RABBITMQ_MANAGE_PORT}:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-php-7.3:
    build:
      context: php-7.3
      dockerfile: Dockerfile
      args:
        PHP_7_3_ENABLE_XDEBUG: ${PHP_7_3_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-7.3
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-7.3/php.ini:/usr/local/etc/php/php.ini
      - ./php-7.3/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_7_3_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:

  dw-php-7.4:
    build:
      context: php-7.4
      dockerfile: Dockerfile
      args:
        PHP_7_4_ENABLE_XDEBUG: ${PHP_7_4_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-7.4
    restart: always
    privileged: true
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php-7.4/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_7_4_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:

  dw-php-8.0:
    build:
      context: php-8.0
      dockerfile: Dockerfile
      args:
        PHP_8_0_ENABLE_XDEBUG: ${PHP_8_0_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-8.0
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-8.0/php.ini:/usr/local/etc/php/php.ini
      - ./php-8.0/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_8_0_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:

  dw-php-8.1:
    build:
      context: php-8.1
      dockerfile: Dockerfile
      args:
        PHP_8_1_ENABLE_XDEBUG: ${PHP_8_1_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-8.1
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-8.1/php.ini:/usr/local/etc/php/php.ini
      - ./php-8.1/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_8_1_PORT}:9000"
    networks:
      - dw-network
  #    extra_hosts:

  dw-php-8.2:
    build:
      context: php-8.2
      dockerfile: Dockerfile
      args:
        PHP_8_2_ENABLE_XDEBUG: ${PHP_8_2_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-8.2
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-8.2/php.ini:/usr/local/etc/php/php.ini
      - ./php-8.2/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_8_2_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:
