version: '3.2'

networks:
  dw-network:

services:

  dw-nginx:
    image: nginx:stable-alpine
    container_name: dw-nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./projects:/var/www
    depends_on:
      - dw-php-7.3
      - dw-php-7.4
      - dw-php-8.0
      - dw-mysql-8.0
      - dw-mysql-5.7
      - dw-mongo-6.0
      - dw-redis-latest
      - dw-rabbitmq-3.11
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-5.7:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-5.7
    restart: always
    volumes:
      - ./mysql-5.7/conf.d:/etc/mysql/conf.d
      - ./mysql-5.7/data:/var/lib/mysql
      - ./mysql-5.7/logs:/var/log/mysql
      - ./mysql-5.7/dump:/dump
    ports:
      - "${MYSQL_5_7_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_5_7_ROOT_PASS}
      MYSQL_USER: ${MYSQL_5_7_USER}
      MYSQL_PASSWORD: ${MYSQL_5_7_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-8.0:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-8.0
    restart: always
    volumes:
      - ./mysql-8.0/conf.d:/etc/mysql/conf.d
      - ./mysql-8.0/data:/var/lib/mysql
      - ./mysql-8.0/logs:/var/log/mysql
      - ./mysql-8.0/dump:/dump
    ports:
      - "${MYSQL_8_0_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_8_0_ROOT_PASS}
      MYSQL_USER: ${MYSQL_8_0_USER}
      MYSQL_PASSWORD: ${MYSQL_8_0_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mongo-6.0: #TODO add 4.x and 5.x services
    image: mongo:6.0
    container_name: dw-mongo-6.0
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-6.0/data:/data/db
      - ./mongo-6.0/conf:/data/configdb
      - ./mongo-6.0/dump:/dump
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-redis-latest:
    image: redis:latest
    container_name: dw-redis-latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-latest/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-latest/data:/var/lib/redis
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-rabbitmq-3.11:
    image: rabbitmq:3.11-management-alpine
    container_name: dw-rabbitmq-3.11
    restart: always
    ports:
      - "${RABBITMQ_CLIENT_PORT}:5672"
      - "${RABBITMQ_MANAGE_PORT}:15672"
    volumes:
      - ./rabbitmq-3.11/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-php-7.3:
    build:
      context: php-7.3
      dockerfile: Dockerfile
      args:
        PHP_7_3_ENABLE_XDEBUG: ${PHP_7_3_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-7.3
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-7.3/php.ini:/usr/local/etc/php/php.ini
      - ./php-7.3/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_7_3_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:

  dw-php-7.4:
    build:
      context: php-7.4
      dockerfile: Dockerfile
      args:
        PHP_7_4_ENABLE_XDEBUG: ${PHP_7_4_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-7.4
    restart: always
    privileged: true
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php-7.4/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_7_4_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:

  dw-php-8.0:
    build:
      context: php-8.0
      dockerfile: Dockerfile
      args:
        PHP_8_0_ENABLE_XDEBUG: ${PHP_8_0_ENABLE_XDEBUG}
        TZ: ${DOCKER_TIMEZONE}
    user: ${DOCKER_UID}:${DOCKER_GID} #<-- here must be UID:GID of current host user
    working_dir: /var/www
    container_name: dw-php-8.0
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./php-8.0/php.ini:/usr/local/etc/php/php.ini
      - ./php-8.0/supervisor.d:/etc/supervisor.d
      - ./projects:/var/www
    ports:
      - "${PHP_8_0_PORT}:9000"
    networks:
      - dw-network
#    extra_hosts:
