version: '3.2'

networks:
  dw-network:

services:

  dw-nginx:
    image: nginx:stable-alpine
    container_name: dw-nginx
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./projects:/var/www
    depends_on:
#      - php-7.3
#      - php-7.4
      - dw-mysql-8.0
      - dw-mysql-5.7
      - dw-redis-7.0
      - dw-mongo-6.0
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-5.7:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-5.7
    restart: always
    volumes:
      - ./mysql-5.7/conf.d:/etc/mysql/conf.d
      - ./mysql-5.7/data:/var/lib/mysql
      - ./mysql-5.7/logs:/var/log/mysql
      - ./mysql-5.7/dump:/dump
    ports:
      - "${MYSQL_5_7_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_5_7_ROOT_PASS}
      MYSQL_USER: ${MYSQL_5_7_USER}
      MYSQL_PASSWORD: ${MYSQL_5_7_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mysql-8.0:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
    container_name: dw-mysql-8.0
    restart: always
    volumes:
      - ./mysql-8.0/conf.d:/etc/mysql/conf.d
      - ./mysql-8.0/data:/var/lib/mysql
      - ./mysql-8.0/logs:/var/log/mysql
      - ./mysql-8.0/dump:/dump
    ports:
      - "${MYSQL_8_0_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_8_0_ROOT_PASS}
      MYSQL_USER: ${MYSQL_8_0_USER}
      MYSQL_PASSWORD: ${MYSQL_8_0_PASS}
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-mongo-6.0:
    image: mongo:6.0
    container_name: dw-mongo-6.0
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongo-6.0/data:/data/db
      - ./mongo-6.0/conf:/data/configdb
      - ./mongo-6.0/dump:/dump
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-redis-7.0:
    image: redis:7.0-alpine
    container_name: dw-redis-7.0
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-7.0/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-7.0/data:/var/lib/redis
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network

  dw-rabbitmq-3.11:
    image: rabbitmq:3.11-management-alpine
    container_name: dw-rabbitmq-3.11
    restart: always
    ports:
      - "${RABBITMQ_CLIENT_PORT}:5672"
      - "${RABBITMQ_MANAGE_PORT}:15672"
    volumes:
      - ./rabbitmq-3.11/plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq-3.11/data:/var/lib/rabbitmq
    environment:
      TZ: ${DOCKER_TIMEZONE}
    networks:
      - dw-network
